### PR TITLE
get rid of class parameters

### LINKED ISSUE #15: strange check in SeoAdminFactory
as per the discussion in https://github.com/symfony-cmf/sonata-admin-integration-bundle/pull/7/files#r90769854 do we have a hard dependency for the burgov bundle for the seo admin, or is it optional? either adjust the wording of the exception, or add checks if we need to throw the exception

### LINKED ISSUE #34: should class parameters be configurable?
see https://github.com/symfony-cmf/sonata-admin-integration-bundle/pull/31#discussion_r91841314

### PR DESCRIPTION
**Pull request by dbu**
fix #34, fix #15

i also did some other cleanups as i stumbled over them.

### CODE REVIEW

**Comment by dbu** [comment]
all php 5.5 builds also fail in master. this seems ready to merge to me.

**Comment by ElectricMaxxx** [comment]
@dbu i don't think so. My branch (which is your target) is green, but we can fix it there?

**Comment by ElectricMaxxx** [comment]
@dbu i missundeststood you arn't pushing against my branch #35 ? can you do so and only do the changes i forgot?

**Comment by dbu** [comment]
> i missundeststood you arn't pushing against my branch #35 ? can you do so and only do the changes i forgot?

ah damn, did not notice you started this as well :-|. you should have assigned the issue to you, maybe then i would have seen you already work on it. closing this and rebased on your branch, lets see

**Comment by ElectricMaxxx** [comment]
ah, sorry, normally i assign every issue/pr forget this one.

**Pull request closed without merging**
