### PR TITLE
Made the bundle PHPCR only

### PR DESCRIPTION
**Pull request by wouterj**
/fixes https://github.com/symfony-cmf/sonata-admin-integration-bundle/issues/61
/replaces https://github.com/symfony-cmf/sonata-admin-integration-bundle/pull/54

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
even when  i don't find the button atm, i agree too.

**Comment by wouterj** [comment]
let's hope travis agrees to.

Should we keep the old package name as well on packagist? Or, as there was no version available yet, should we just delete the old package name from packagist?

**Comment by dbu** [comment]
> Should we keep the old package name as well on packagist? Or, as there
> was no version available yet, should we just delete the old package name
> from packagist?

i'd just rename this repo and remove everything. nobody should already
be using this.

**Comment by ElectricMaxxx** [comment]
I did. But no worries.

**Comment by wouterj** [comment]
Let me introduce you to `Symfony\Cmf\Bundle\SonataPhpcrAdminIntegrationBundle\DependencyInjection\CmfSonataPhpcrAdminIntegrationExtension` :D (class name lengths have reached Java-level).

Tests seem to pass, so I'll merge this one soon and rename the package on packagist.

**Comment by ElectricMaxxx** [comment]
aahhhh ... @wouterj  one thing:
Shouldn't we introduce the world `phpcr` into the service defintion names too?

**Comment by wouterj** [comment]
> Shouldn't we introduce the world phpcr into the service defintion names too?

I did that sometime this afternoon. Everything now is `SonataPhpcrAdminIntegrationBundle` or `cmf_sonata_phpcr_admin_integration`.

**Comment by wouterj** [comment]
Hmm, the only way is to abandon and create a new package with the new name. So it seems like we can't delete it. /cc @Seldaek

**Comment by wouterj** [comment]
Oh nvm, @ElectricMaxxx can probably delete the package. Can you please do that? :)

**Comment by ElectricMaxxx** [comment]
@wouterJ it will hurt but I can do it tonight.

**Comment by ElectricMaxxx** [comment]
@wouterj i abandoned the old one. Can you maybe add me as maintainer to the new one too, as i did for you with the old one?

**Comment by wouterj** [comment]
@ElectricMaxxx we decided to remove the package. Can you please hit the "delete" button?

And added you as maintainer

**Comment by ElectricMaxxx** [comment]
auswahl_078
I have no chance to delete, that is really strange the repo itself correlates to the new name (branches, homepage) but the name is the old one on packagist

**Comment by wouterj** [comment]
Hmm, that's weird. I do have a delete button for the `symfony-cmf/sonata-phpcr-admin-integration-bundle` (the new one). Let's keep it abandoned then (and wait for @Seldaek for help, a typo is quickly made here 😅

**Comment by ElectricMaxxx** [comment]
Maybe @naderman could help us too.

**Pull request merged**
