### PR TITLE
Integrated the RoutingBundle admins

### PR DESCRIPTION
**Pull request by wouterj**

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
Looks nice.

Any chance to activate the extensions and test that?

**Comment by wouterj** [comment]
I don't really like the unit tests of extensions and DI stuff. They contain lot's of assertions that'll change each time you edit something in a DI class.

The web tests already test all admins, so also their configuration.

**Comment by ElectricMaxxx** [comment]
mh indeet, that is a good point. I saw them as an easy way of writing tests to see if the extension is working well.

No i saw the AdminExtension test. 

Ok, Code looks good. Can we do something for the tests here? Shall we support Symfony 3.2 in here when sonata does not support it?

**Comment by wouterj** [comment]
> Ok, Code looks good. Can we do something for the tests here? Shall we support Symfony 3.2 in here when sonata does not support it?

Nope, not that much. It's just waiting for Sonata atm. And yes, of course we should support 3.2 😸

**Comment by ElectricMaxxx** [comment]
then this PR LGTM.

**Pull request merged**
